apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-grafana-datasource
  namespace: tracing
  labels:
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo.tracing.svc.cluster.local:3200
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            filterByTraceID: true
            tags:
              - key: 'service.name'
                value: 'app'
          lokiSearch:
            datasourceUid: loki